# Generated by Django 3.2.21 on 2023-09-11 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portafolio', '0003_contacto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Referencias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('puesto', models.CharField(max_length=15)),
                ('empresa', models.CharField(max_length=15)),
                ('telefono', models.CharField(max_length=15)),
            ],
        ),
    ]
