# Generated by Django 3.2.21 on 2023-09-11 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portafolio', '0006_perfil'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='profesion',
            field=models.CharField(max_length=100),
        ),
    ]
